"""Export tabulated I-V curves to CSV for PLECS lookup tables.

WORK IN PROGRESS: the CSV format and grid density are a first guess at
what the PLECS side needs; expect both to change once the PLECS model of
the SEPIC stage exists and the plant-vs-plant comparison is actually run.

PLECS models the panel as a voltage-controlled current source driven by a
1-D lookup table. This script dumps the exact I-V curves the Python
simulation uses (the pvlib-fitted Hissuma PSF10MONO string behind
``TabulatedPanel``) so that the plant-vs-plant comparison of the
sim-to-real protocol (see docs/methodology.md) runs both simulators on the
*same* panel curve.

One CSV per condition of the fixed test-case bank (``harness/compare_bank``):
full sun and the shade-cloth case. Columns: ``v`` [V], ``i`` [A], with a
provenance header. A README.md in the output directory documents how the
files were generated.

Run with::

    uv run scripts/export_iv_plecs.py
"""

from datetime import date
from pathlib import Path

import numpy as np

import mpp_sdk
from harness.compare_bank import FULL, SHADED
from harness.panel_config import shaded_string

N_POINTS = 1000
OUT_DIR = Path(__file__).resolve().parent.parent / "data" / "plecs"

README = """\
# PLECS panel lookup tables

**Work in progress**: format and grid density are a first guess; they
will change once the PLECS SEPIC model exists and the plant-vs-plant
comparison is actually run.

Generated by `scripts/export_iv_plecs.py` (regenerate, do not edit).

Each CSV is the I-V curve of the 2x Hissuma PSF10MONO series string
(pvlib De Soto fit, see `mpp_sdk/models/pvlib_adapter.py`) at the
per-panel irradiance in the file name, tabulated on a {n}-point voltage
grid from 0 to V_oc at 25 degC. Wire it into PLECS as a 1-D lookup
table feeding a voltage-controlled current source.

These are the same curves the Python harness simulates against, so a
PLECS run and a `harness/compare_bank.py` run share the same panel by
construction (plant-vs-plant layer of the sim-to-real protocol in
docs/methodology.md).

Last generated: {today}.
"""


def export(irr: tuple[float, float], out_dir: Path) -> Path:
    panel = mpp_sdk.TabulatedPanel(shaded_string(irr), n=N_POINTS)
    v = np.linspace(0.0, panel.open_circuit_voltage, N_POINTS)
    i = panel.current(v)
    path = out_dir / f"iv_{irr[0]:.0f}_{irr[1]:.0f}.csv"
    v_mp, i_mp, p_mp = panel.mpp()
    np.savetxt(
        path,
        np.column_stack([v, i]),
        delimiter=",",
        header=(
            f"2x Hissuma PSF10MONO series, irradiance {irr[0]:.0f}/{irr[1]:.0f} W/m2, 25 degC\n"
            f"global MPP: V={v_mp:.3f} V, I={i_mp:.3f} A, P={p_mp:.3f} W\n"
            "v,i"
        ),
        fmt="%.6f",
    )
    return path


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for irr in (FULL, SHADED):
        print(f"wrote {export(irr, OUT_DIR)}")
    readme = OUT_DIR / "README.md"
    readme.write_text(README.format(n=N_POINTS, today=date.today().isoformat()))
    print(f"wrote {readme}")


if __name__ == "__main__":
    main()
