M48
; DRILL file KiCad 10.0.1 date 2026-06-07T22:21:57
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-07T22:21:57-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X3.197Y-2.2425
X3.388Y-2.2425
T2
X3.1852Y-2.1232
X3.3998Y-2.1232
M30
